default.check-filename = true

[default.extend-words]
actived = "actived"
colum = "colum"
loosing = "loosing"
nd = "nd"

[files]
extend-exclude = ["CHANGELOG.md", "*.snap", "test/config/jest.base.conf.js"]
